---
owner: IWLEntertainment
repo: upptime
sites:
  - name: Webserver
    url: 63.141.255.191
    port: 80
    check: tcp-ping
status-website:
  theme: ocean
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/IWLEntertainment/upptime/master/assets/justuptowngames_logo.png
  name: "Just Uptown Games - Status (powered by Upptime)"
  introTitle: "Web Services Monitor"
  introMessage: This status page provides updates for the Just Uptown Games webstore servers.<br><br>If you visit the main justuptowngames.com website and notice a slowdown in the web server or unresponsive emails, check this page for updates. We should have an update here about it.<br><br>In the event of any major outages, there will be an update here.
  navbar:
    - title: Status
      href: /
    - title: Catalog
      href: https://www.justuptowngames.com
    - title: Help Desk
      href: https://help.justuptowngames.com
assignees:
  - retched
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
  locale: en-US
